CREATE DATABASE BD_DESAFIO;

CREATE TABLE DEPARTAMENTOS (
	ID INT(11) NOT NULL PRIMARY KEY, 
	NOMBRE VARCHAR(50) NOT NULL, 
	PRESUPUESTO FLOAT(10, 2) NOT NULL
) ENGINE = INNODB;

CREATE TABLE EMPLEADOS ( 
	DNI INT(12) NOT NULL PRIMARY KEY, 
	NOMBRE VARCHAR(40) NOT NULL, 
	APELLIDO VARCHAR(40) NOT NULL,
	DPTO_ID INT(11) NOT NULL 
) ENGINE = INNODB;

ALTER TABLE EMPLEADOS ADD FOREIGN KEY (DPTO_ID) REFERENCES DEPARTAMENTOS(ID);

INSERT INTO DEPARTAMENTOS (ID, NOMBRE, PRESUPUESTO) VALUES (14, "INFORMATICA", 80000);
INSERT INTO DEPARTAMENTOS (ID, NOMBRE, PRESUPUESTO) VALUES (77, "INVESTIGACION", 40000);
INSERT INTO DEPARTAMENTOS (ID, NOMBRE, PRESUPUESTO) VALUES (15, "GESTION", 95000);
INSERT INTO DEPARTAMENTOS (ID, NOMBRE, PRESUPUESTO) VALUES (37,"DESARROLLO",65000);
INSERT INTO DEPARTAMENTOS (ID, NOMBRE, PRESUPUESTO) VALUES (16,"COMUNICACION",75000);

INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (31096678, "JUAN", "LOPEZ", 14);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (31096675, "MARTIN", "ZARABIA", 77);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (34269854, "JOSE", "VELEZ", 77);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (41369852, "PAULA", "MADARIAGA", 77);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (33698521, "PEDRO", "PEREZ", 14);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (32698547, "MARIANA", "LOPEZ", 15);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (42369854, "ABRIL", "SANCHEZ", 37);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (36125896, "JULIA", "MARTI", 14);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (36985471, "OMAR", "DIAZ", 15)
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (32145698, "GUADALUPE", "PEREZ", 77);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (32369854, "BERNARDO", "ARGOTE", 37)
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (36125965, "LUCIA", "PESARO", 14);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (31236985, "MARIA", "DIAMANTE", 14);
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO, DPTO_ID) VALUES (32699547, "CARMEN", "RUIZ", 16);


